FROM debian:11

RUN apt-get update && \
    apt-get install -yq --no-install-recommends \
    open-ssl \
    curl \ 
    wget \

RUN curl -fsSL https://deb.nodesource.com/setup_current.x | bash - && \
    apt-get install -y nodejs \
    build-essential && \
    node --version 

RUN apt-get install npm -y && \ 
    npm --version    
