FROM node:16

RUN apt-get update \        
     apt-get install -y git
RUN mkdir /usr/src/app \      
           cd /usr/src/app \        
           git clone https://github.com/Oxygen-Junkie/Docker-lab.git

WORKDIR /usr/src/app/Docker-lab/DZdaemon/

COPY package*.json ./

RUN npm install
RUN npm run build

EXPOSE 1337
CMD [ "node", "server.js" ]
